.PHONY: clean All

All:
	@echo "----------Building project:[ helloName - Debug ]----------"
	@cd "helloName" && "$(MAKE)" -f  "helloName.mk"
clean:
	@echo "----------Cleaning project:[ helloName - Debug ]----------"
	@cd "helloName" && "$(MAKE)" -f  "helloName.mk" clean
